name: lesson_3
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+1 # Versiya va build raqami

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # 5.0.0 emas, eng oxirgi mos versiya

flutter:
  uses-material-design: true

  assets:
    - assets/images/
